backend calib eyetracker
FrancisCardinal/RAVE pull request #15
Opened 2022-02-26 01:04 UTC by amelierioux

Backend for eye tracking calibration
What is left to do:
- Change the gifs for the real ones
- In python file, setup the calibration "flags" depending on the main infrastructure (pub sub?)

2022-02-26 16:44 UTC, aRedCarrot approved these changes

2022-02-27 16:11 UTC, FrancisCardinal requested changes
Super bon travail ! Il te restera juste à prendre une décision par rapport au commentaire que je t'ai mis !

2022-02-27 16:11 UTC, FrancisCardinal commented on rave-web/src/translations/en/common.js
> +    errorMessage: 'The name you have chosen alreay exists, choose another one.',
Sur le disque / dans la database, j'imagine qu'on pourrait utiliser autre chose que les noms comme clé / on pourrait supporter plusieurs profils avec le même nom ; Pour différencier deux personnes qui ont le même nom dans le frontend, j'imagine qu'à ce moment-là, on pourrait afficher le nom couplé à un autre attribut (ex: date de création du profil). 

Bref, si tu penses que c'est pertinent à supporter, c'est pas un problème fondamental ; si tu penses que les chances sont rares que, localement, on ait deux personnes avec exactement le même nom et qu'on fait une preuve de concept de toute façon, ça peut rester de même !

2022-02-27 16:11 UTC, FrancisCardinal commented on rave-web/src/translations/fr/common.js
> +    errorMessage: 'Le nom que vous avez choisi existe déjà, choisir un nouveau.',
Même principe que mon autre commentaire

2022-02-27 16:24 UTC, merged