Vision algo optimize
FrancisCardinal/RAVE pull request #31
Opened 2022-09-29 15:13 UTC by AnthonyGosselin

Bringing optimizations to the vision algorithme

2022-09-30 15:53 UTC, AnthonyGosselin commented
@FrancisCardinal Just confirm that the changes to the EyeTracking files are correct. I must have merged with Master at some point...

2022-10-01 01:28 UTC, FrancisCardinal requested changes

2022-10-01 01:28 UTC, FrancisCardinal commented on library/RAVE/src/RAVE/eye_tracker/EyeTrackerDatasetBuilder.py
> +                ORIGINAL_HEIGHT, ORIGINAL_WIDTH, EyeTrackerDataset.CROP_SIZE
@AnthonyGosselin , ça c'est pas bon, il faut garder le self._CROP_SIZE

2022-10-01 01:28 UTC, FrancisCardinal commented on library/RAVE/src/RAVE/eye_tracker/EyeTrackerTrainer.py
>              total_visible_pupils += visibility.sum()
Même chose ici, il faudrait garder ce qui est dans la colonne de gauche

2022-10-02 21:00 UTC, AnthonyGosselin commented on library/RAVE/src/RAVE/eye_tracker/EyeTrackerTrainer.py
>              total_visible_pupils += visibility.sum()
Dans le fond, est-ce que je revert tous les changements pour les 3 fichiers de Eye tracker (EyeTrackerTrainer, EyeTrackerDatasetBuilder et EyeTrackerModel)?

2022-10-03 17:20 UTC, FrancisCardinal commented on library/RAVE/src/RAVE/eye_tracker/EyeTrackerTrainer.py
>              total_visible_pupils += visibility.sum()
Oui, ça serait la bonne chose à faire je pense !

2022-10-04 14:07 UTC, FrancisCardinal approved these changes

2022-10-04 18:14 UTC, merged