Vision verifier improve
FrancisCardinal/RAVE pull request #33
Opened 2022-10-04 18:20 UTC by AnthonyGosselin

General improvements including:
- Optimized waiting in loops (no useless waiting, do not execute on the same frame twice)
- New IOU computation method: Generalized IOU
- Calling verifier during face association step: avoid id-swtiching

2022-10-04 18:47 UTC, AnthonyGosselin commented
@JacobKealey J'ai changé le max line length de flake8 à 120 plutôt que 79, 79 c'était vraiment trop, court. Je l'ai inclu dans ce PR. juste valider que ça a été bien fait

2022-10-06 18:36 UTC, JacobKealey approved these changes

2022-10-06 18:42 UTC, JacobKealey requested changes
Faut rajouter la max line length dans le worflow de github

2022-10-06 19:08 UTC, JacobKealey approved these changes

2022-10-06 19:10 UTC, merged