Audio dataset generator
FrancisCardinal/RAVE pull request #9
Opened 2022-01-31 18:26 UTC by EtienneDS

Generator to create audio dataset. 

Uses sources and noises from microsoft dataset (https://github.com/microsoft/MS-SNSD).
Will be called by script (added) or directly through audio dataset handler (to come).

Generates wav files with combines speech and noise, as well as ground truth (speech and noise masks).
Uses RIR to generate mono audio to multiple microphones.

2022-01-31 19:16 UTC, JacobKealey requested changes, later dismissed
Is there a reason why there's an empty file (pyoades_test)?

2022-01-31 19:16 UTC, JacobKealey commented on library/RAVE/src/RAVE/audio/Dataset/DatasetBuilder_config.yaml
> +room:
Can you add a comment on how to define a room? AKA what this array means

2022-02-03 14:39 UTC, JacobKealey approved these changes

2022-02-03 15:06 UTC, felixducharme321 approved these changes

2022-02-03 15:08 UTC, merged